### ISSUE TITLE
Update domain list

### ISSUE THREAD

**Issue by voku** [diegomagikal/laravel-tempmail#1]
Hi, some time ago I also try to detect temp mail adresses, but I didn't found a good way to collect / fetch / upgrade the current temp-domains... Here is my outdated list: https://github.com/voku/email-check/blob/master/src/voku/helper/data/domainsTemporary.php

So this list is not complete and never will be... have you any idea how to fix this? Is there any api or free service we can use? 

Bests, 
Lars Moelleken

**Comment by diegomagikal** [comment]
Hi.. I'm using [SimpleHmlDom](http://simplehtmldom.sourceforge.net/) to crawl regularly the mail temp sites and extract all domains found. I think that it is a good way!

**Comment by diegomagikal** [comment]
In your list, there are several [free domains TLD's](http://www.freenom.com/en/freeandpaiddomains.html). You can simply make a rule to block all them!

**Comment by voku** [comment]
Good idea, I removed ~15k domain with the excluding of all the free domains. :+1:
